# Generated by Django 6.0.1 on 2026-01-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING'), ('OVERDUE', 'OVERDUE')], default='PENDING', max_length=10),
        ),
    ]
