# Generated by Django 6.0.1 on 2026-01-21 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_email',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENING'), ('OVERDUE', 'OVERDUE')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('lesson_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.student')),
            ],
        ),
    ]
