# Generated by Django 6.0.1 on 2026-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_student_parent_email_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
