# Generated by Django 6.0.1 on 2026-02-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_files/'),
        ),
    ]
