# Generated by Django 6.0.1 on 2026-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
